### ISSUE TITLE
Upcoming metadata changes

### ISSUE THREAD

**Issue by cjihrig** [nodejs/llnode#158] opened 2017-12-19 16:07 UTC
The following changes are coming:

- `v8dbg_class_Map__inobject_properties_or_constructor_function_index__int`
  - This is now `v8dbg_class_Map__inobject_properties_start_or_constructor_function_index__char` as of https://github.com/v8/v8/commit/61bf2cc69217a4e9c7a40bb74269508fa26c2062
- `v8dbg_class_Map__instance_attributes__int`
  - This is now `v8dbg_class_Map__instance_type__uint16_t` as of https://github.com/v8/v8/commit/c00bb6da1cef9f7e9dab842904232255717f8291 and https://github.com/v8/v8/commit/cb46310a799eb0d60a613ead0af8c8200c5338b1
- `v8dbg_class_Map__instance_size__int`
  - This is now `v8dbg_class_Map__instance_size_in_words__char` as of https://github.com/v8/v8/commit/61bf2cc69217a4e9c7a40bb74269508fa26c2062
- `v8dbg_bit_field3_dictionary_map_shift`
  - This is now `v8dbg_bit_field3_is_dictionary_map_shift` as of https://github.com/v8/v8/commit/7a159da151e5f5437d6924de4fd142f854d3df4e

See https://github.com/nodejs/node-v8/pull/34

**Comment by mmarchini** [comment] 2018-02-05 23:18
These metadata changes landed with https://github.com/nodejs/node/pull/17489, thus llnode is not working with `node` compiled from source. There's also one more missing: `v8dbg_prop_type_mask`.

**Comment by cjihrig** [comment] 2018-02-06 02:42
> There's also one more missing: v8dbg_prop_type_mask.

That one is expected. It's used [here](https://github.com/nodejs/llnode/blob/20b14d967ecfe60a3b778611de04bad4f59b14b9/src/llv8-constants.cc#L461-L463) for Node.js version detection.

**Comment by mmarchini** [comment] 2018-05-01 19:50
I think we should reopen this Issue, we updated the metadata names, but we didn't fix semantic changes. `npm test` have six failing tests on Node.js v10.0.0.

I started to investigate them, and I think at least three failures are happening because of https://github.com/v8/v8/commit/61bf2cc69217a4e9c7a40bb74269508fa26c2062. If I understood the patch correctly, it moved the internal properties of `Map`, confusing llnode once it tries to inspect objects. For example, in our inspect-test, Class.x should be 1 and Class.hashmap should be an object, but instead, they both are pointing to the internal Map: 

```
(lldb) v8 findjsinstances -d Class
0x000030c00446cd11:<Object: Class properties {
    .x=0x000030c077382341:<Map own_descriptors=0 in_object=0 instance_size=8 descriptors=0x000030c0b6e02231>,
    .y=0.000000,
    .hashmap=0x000030c077382341:<Map own_descriptors=0 in_object=0 instance_size=8 descriptors=0x000030c0b6e02231>}
  internal fields {
    0x0000000100000000,
      0x405edd2f1a9fbe77,
      0x000030c00446ce09,
      0x000030c077382341,
      0x000030c077382341,
      0x000030c077382341,
      0x000030c077382341,
      0x000030c077382341}>
```

FWIW all failures from `npm test` can be reproduced with `v10.0.0-v8-canary20171123e31a70aef2` from https://nodejs.org/download/v8-canary/, which means changes made on v8/v8@7a159da should already be fixed in llnode 😄

**Closed** 2018-05-15 18:36 UTC
